name = "fantasy-football-app"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[env.production]
route = "texasperfect.win/*"

[build]
command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"